name: conseiller_app
description: Application offline pour conseillers agricoles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP et synchronisation
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  
  # État et navigation
  provider: ^6.1.1
  go_router: ^12.1.3
  
  # Base de données locale
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Géolocalisation
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Stockage sécurisé
  flutter_secure_storage: ^9.0.0
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  
  # Photos
  image_picker: ^1.0.4
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true